version: '3.8'
services:
  reflex-app:
    build: .
    container_name: reflex_stock_graph_app
    ports:
      - "8003:8001"
      - "3003:3001"
    env_file:
      - ./stock_graph_app/.env
    # environment:
    #   - GOOGLE_SHEET_CSV_URL=${GOOGLE_SHEET_CSV_URL}
    volumes:
      - .:/app
    restart: unless-stopped
