name: Create Template Artifacts on Release

on:
  release:
    types: [published]

jobs:
  create-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create artifacts
        run: |
          mkdir artifacts
          for dir in $(ls -d */); do
            zip -r "artifacts/${dir%/}.zip" "$dir"
          done
          ls artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: subfolder-artifacts
          path: artifacts/
