name: Create Artifacts on Push

on:
  push:
    branches:
      - alek/artifacts # Specify the branches you want to trigger this action on

jobs:
  create-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create and upload artifacts
        run: |
          for dir in $(ls -d */); do
            zip_name="${dir%/}.zip"
            echo "Creating zip $zip_name"
            zip -r "$zip_name" "$dir"
            echo "Uploading $zip_name"
            gh_path="$zip_name"
            gh name="upload-artifact"
            uses: actions/upload-artifact@v3
            with:
              name: "${zip_name}"
              path: "${zip_name}"
          done
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
