name: Create Artifacts on Push

on:
  push:
    branches:
      - alek/artifacts # Specify the branches you want to trigger this action on

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip subfolders
        run: |
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done

      - name: Upload artifacts
        run: |
          for file in *.zip; do
            name=$(basename "$file" .zip)
            echo "Uploading $file as $name"
            gh run upload-artifact --name "$name" "$file"
          done
