name: Zip and Publish Subfolders

on:
  release:
    types: [published]

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list_zip_files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip files for each subfolder
        run: |
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
            zip -r "${dir##*/}.zip" "$dir"
          done

      - name: List and collect zip files
        id: collect_zip_files
        run: |
          # List the zip files and convert them into a JSON array
          files=$(ls *.zip)
          echo "Generated zip files: $files"

          # Format files as a JSON array
          json_files=$(echo $files | jq -R -s -c 'split(" ")')
          echo "files=$json_files" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug output
        run: |
          echo "Files: ${{ env.files }}"

  upload-artifacts:
    needs: zip-and-publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.zip-and-publish.outputs.files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.file }}
          asset_name: ${{ matrix.file }}
          asset_content_type: application/zip
