name: Release

on:
  push:
    tags:
      - "v*" # This triggers the workflow on tags matching the pattern v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List subfolders for debugging
        run: ls -d */

      - name: Zip subfolders
        run: |
          for d in */ ; do
            if [ -d "$d" ]; then
              zip -r "${d%/}.zip" "$d"
            fi
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          for file in *.zip; do
            asset_name="${file%.zip}_${{ github.ref }}.zip"
            echo "Uploading $file as $asset_name"
            curl \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/zip" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$asset_name"
          done
