name: Create Template Artifacts on Release

on:
  push:
    branches:
      - alek/artifacts

jobs:
  create-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create and upload artifacts
        run: |
          for dir in $(ls -d */); do
            zip -r "${dir%/}.zip" "$dir"
            echo "::set-output name=artifact_name::${dir%/}.zip"
            echo "::set-output name=artifact_path::${dir%/}.zip"
          done
        id: create_artifacts

      - name: Upload artifacts
        run: |
          for dir in $(ls -d */); do
            zip_name="${dir%/}.zip"
            echo "Uploading $zip_name"
            gh_path="$zip_name"
            gh name="upload-artifact"
            with:
              name: "${zip_name}"
              path: "${zip_name}"
