name: Create Artifacts on Push

on:
  push:
    branches:
      - alek/artifacts # Specify the branches you want to trigger this action on

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup zip utility
        run: sudo apt-get install -y zip

      - name: List subfolders and zip them
        run: |
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done

      - name: Upload zips as artifacts
        run: |
          for dir in */ ; do
            artifact_name="${dir%/}"
            artifact_path="${artifact_name}.zip"
            echo "Uploading ${artifact_name} as ${artifact_path}"
            echo "${artifact_name}=${artifact_path}" >> $GITHUB_ENV
          done

      - name: Upload each artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
