version: '3'

services:
  # Frontend service
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./.web:/app
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install && npm run dev"
    networks:
      - reflex-network
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/.web
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - REFLEX_FRONTEND_URL=http://localhost:3000
      - REFLEX_BACKEND_URL=http://localhost:8000
    networks:
      - reflex-network

networks:
  reflex-network:
    driver: bridge
